force-app/main/default/objects/Account/fields/user_id__c.field-meta.xml
<CustomField>
    <fullName>user_id__c</fullName>
    <label>クライアントID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomOpportunity__c/CustomOpportunity__c.object-meta.xml
<CustomObject>
    <label>C商談</label>
    <nameField>
        <label>商談ID</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomOpportunity__c/fields/background__c.field-meta.xml
<CustomField>
    <fullName>background__c</fullName>
    <label>商談の経緯</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>代理店からの問い合わせ</fullName>
            </value>
            <value>
                <fullName>広告主からの問い合わせ</fullName>
            </value>
            <value>
                <fullName>外部からの紹介</fullName>
            </value>
            <value>
                <fullName>社内からの紹介</fullName>
            </value>
            <value>
                <fullName>自分の知り合い</fullName>
            </value>
            <value>
                <fullName>リピート</fullName>
            </value>
            <value>
                <fullName>以前からの提案</fullName>
            </value>
            <value>
                <fullName>自社広告</fullName>
            </value>
            <value>
                <fullName>イベント</fullName>
            </value>
            <value>
                <fullName>自主提案</fullName>
            </value>
            <value>
                <fullName>コンペ</fullName>
            </value>
            <value>
                <fullName>その他</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomOpportunity__c/fields/clent_name__c.field-meta.xml
<CustomField>
    <fullName>clent_name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>社名</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>C商談</relationshipLabel>
    <relationshipName>C</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomOpportunity__c/fields/syoudan_c_date__c.field-meta.xml
<CustomField>
    <fullName>syoudan_c_date__c</fullName>
    <label>刈り取り時期</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CustomOpportunity__c/fields/syoudan_status__c.field-meta.xml
<CustomField>
    <fullName>syoudan_status__c</fullName>
    <label>商談の状態</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>訪問</fullName>
            </value>
            <value>
                <fullName>提案中</fullName>
            </value>
            <value>
                <fullName>検討C</fullName>
            </value>
            <value>
                <fullName>検討B</fullName>
            </value>
            <value>
                <fullName>検討A</fullName>
            </value>
            <value>
                <fullName>内定</fullName>
            </value>
            <value>
                <fullName>成約</fullName>
            </value>
            <value>
                <fullName>否決</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Menu__c/Menu__c.object-meta.xml
<CustomObject>
    <label>メニュー</label>
    <nameField>
        <label>メニューID</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Menu__c/fields/custom_opportunity__c.field-meta.xml
<CustomField>
    <fullName>custom_opportunity__c</fullName>
    <label>C商談</label>
    <referenceTo>CustomOpportunity__c</referenceTo>
    <relationshipLabel>メニュー</relationshipLabel>
    <relationshipName>ZhGB</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Menu__c/fields/syoudan_status__c.field-meta.xml
<CustomField>
    <fullName>syoudan_status__c</fullName>
    <formula>TEXT(custom_opportunity__r.syoudan_status__c)</formula>
    <label>商談状態</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SeisakuSettei__c/SeisakuSettei__c.object-meta.xml
<CustomObject>
    <label>制作設定</label>
    <nameField>
        <label>制作設定ID</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SeisakuSettei__c/fields/seisaku_siharai__c.field-meta.xml
<CustomField>
    <fullName>seisaku_siharai__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>制作・支払</label>
    <referenceTo>SeisakuSiharai__c</referenceTo>
    <relationshipLabel>制作設定</relationshipLabel>
    <relationshipName>eGBh</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SeisakuSiharai__c/SeisakuSiharai__c.object-meta.xml
<CustomObject>
    <label>制作・支払</label>
    <nameField>
        <label>制作・支払ID</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SeisakuSiharai__c/fields/menu__c.field-meta.xml
<CustomField>
    <fullName>menu__c</fullName>
    <label>メニューID</label>
    <referenceTo>Menu__c</referenceTo>
    <relationshipLabel>制作・支払</relationshipLabel>
    <relationshipName>a8Ep</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SeisakuSiharai__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>タイプ</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>記事広告制作</fullName>
            </value>
            <value>
                <fullName>その他制作・支払</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SeisakuSiharai__c/recordTypes/new.recordType-meta.xml
<RecordType>
    <fullName>new</fullName>
    <active>true</active>
    <label>00:新規</label>
</RecordType>

force-app/main/default/classes/CommonIdInsertHandlerTest.cls
/**--------------------------------------------------------------------------
 * プログラム名 ：ID採番処理ハンドラー（共通）テストクラス
 * 作成日        ：2019/08/08
 * 作成者        ：Sou
 * コピーライト   ：株式会社東洋経済新報社　TOYO KEIZAI INC. Limited Copyright (c) 2017 
 *----------------------------------------------------------------------------
 * 修正履歴（修正日：担当者：修正内容）
 * 2019/08/08:Sou:新規作成
 *----------------------------------------------------------------------------
 */
@isTest
private class CommonIdInsertHandlerTest {
    //取引先から行動までの主従オブジェクトのIDを採番する
    static testMethod void unitTest1() {
        //取引先の新規入力
        Account accnt = new Account(name = 'Test_00001',user_id__c='00001');
        insert accnt;
        //C商談の新規入力
        Account accnt2 = [select Id from Account where name = 'Test_00001'];
        CustomOpportunity__c oppo = new CustomOpportunity__c(
        name = '*',syoudan_c_date__c=Date.today(),syoudan_status__c='訪問',background__c='代理店からの問い合わせ',clent_name__c=Accnt2.ID);
        insert oppo;
        //メニューの新規入力
        CustomOpportunity__c oppo2 = [select Id from CustomOpportunity__c where name = '00001_01'];
        Menu__c menu = new Menu__c(name='*',custom_opportunity__c=oppo2.Id);
        insert menu;
        //制作・支払の新規入力
        Menu__c menu2 = [select Id from Menu__c where name = '00001_01_01'];
        SeisakuSiharai__c siha = new SeisakuSiharai__c(name='*',Type__c='その他制作・支払',menu__c=menu2.Id);
        insert siha;
        //制作設定の新規入力
        SeisakuSiharai__c siha2 = [select Id from SeisakuSiharai__c where name = '00001_01_01_001'];
        SeisakuSettei__c sett = new SeisakuSettei__c(name='*',seisaku_siharai__c=siha2.Id);
        insert sett;
        //制作設定の新規入力 （C商談から）
        Task task = new Task(Subject='Test_00001',OwnerId='0057F000001Zc39QAC',WhatId=oppo2.Id);
        insert task;
        //制作設定の新規入力（取引先から） 
        Task task2 = new Task(Subject='Test_00001',OwnerId='0057F000001Zc39QAC',WhatId=Accnt2.ID);
        insert task2;
        //制作設定の新規入力 （C商談から）
        Event event = new Event(Subject='Test_00001',OwnerId='0057F000001Zc39QAC',StartDateTime=Datetime.now(),EndDateTime=Datetime.now(),WhatId=oppo2.Id);
        insert event;
        //制作設定の新規入力（取引先から） 
        Event event2 = new Event(Subject='Test_00001',OwnerId='0057F000001Zc39QAC',StartDateTime=Datetime.now(),EndDateTime=Datetime.now(),WhatId=Accnt2.ID);
        insert event2;
    }

}